# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JZProject' do
pod 'AFNetworking', '~> 3.0'
pod 'SVProgressHUD'
pod 'Toast'
pod 'JPush'
pod 'MJRefresh'
pod 'SDWebImage', '~> 5.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JZProject

  target 'JZProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JZProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
